
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzalrnwnpzbpzvcrjitt.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxybnducHpicHp2Y3JqaXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjEwMjUsImV4cCI6MjA2MzIzNzAyNX0.-YpKnsjN8rZpDtWWmgcWNtrfAz8-KEh7KZtwp1vFKX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export const SUPABASE_API_URL = SUPABASE_URL;
