// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzalrnwnpzbpzvcrjitt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6YWxybnducHpicHp2Y3JqaXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjEwMjUsImV4cCI6MjA2MzIzNzAyNX0.-YpKnsjN8rZpDtWWmgcWNtrfAz8-KEh7KZtwp1vFKX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// W kontekstach niezabezpieczonych (http://) przeglądarka blokuje Web Locks API
// ("LockManager.request: request() is not allowed in this context").
// Używamy wtedy prostej kolejki w pamięci zamiast navigator.locks.
let lockChain: Promise<unknown> = Promise.resolve();

const memoryLock = async <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => {
  const run = lockChain.then(fn, fn);
  lockChain = run.catch(() => {});
  return run;
};

const supportsWebLocks = (() => {
  try {
    return typeof navigator !== 'undefined' && !!navigator.locks && window.isSecureContext;
  } catch {
    return false;
  }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    ...(supportsWebLocks ? {} : { lock: memoryLock }),
  },
});
